[2021-09-16 22:04:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:14:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:15:36,516] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-39359e28-f4f1-44de-9fa9-a2d564e54b21] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:36,516] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 1 (__consumer_offsets-0) (reason: removing member consumer-3-39359e28-f4f1-44de-9fa9-a2d564e54b21 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:36,516] INFO [GroupCoordinator 0]: Group order with generation 2 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:38,923] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-c7972135-9304-4280-b0a1-a75b26b40aa5] in group delivery has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:38,923] INFO [GroupCoordinator 0]: Preparing to rebalance group delivery in state PreparingRebalance with old generation 1 (__consumer_offsets-46) (reason: removing member consumer-3-c7972135-9304-4280-b0a1-a75b26b40aa5 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:38,923] INFO [GroupCoordinator 0]: Group delivery with generation 2 is now empty (__consumer_offsets-46) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:41,361] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-61623fbe-dfc9-45f8-bd14-bc5914223cea] in group product has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:41,362] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 3 (__consumer_offsets-15) (reason: removing member consumer-3-61623fbe-dfc9-45f8-bd14-bc5914223cea on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:41,362] INFO [GroupCoordinator 0]: Group product with generation 4 is now empty (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:53,627] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group delivery in Empty state. Created a new member id consumer-3-54e5eb0c-015e-42fc-beec-c21de5dff7b9 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:53,628] INFO [GroupCoordinator 0]: Preparing to rebalance group delivery in state PreparingRebalance with old generation 2 (__consumer_offsets-46) (reason: Adding new member consumer-3-54e5eb0c-015e-42fc-beec-c21de5dff7b9 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:53,628] INFO [GroupCoordinator 0]: Stabilized group delivery generation 3 (__consumer_offsets-46) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:15:53,632] INFO [GroupCoordinator 0]: Assignment received from leader for group delivery for generation 3 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:24:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:26:48,516] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group product in Empty state. Created a new member id consumer-3-0077e9bb-69f2-47d4-ac49-ef7deeffc6e6 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:48,517] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 4 (__consumer_offsets-15) (reason: Adding new member consumer-3-0077e9bb-69f2-47d4-ac49-ef7deeffc6e6 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:48,518] INFO [GroupCoordinator 0]: Stabilized group product generation 5 (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:48,521] INFO [GroupCoordinator 0]: Assignment received from leader for group product for generation 5 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:58,001] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-78aa3221-4245-4ca5-a671-6b4a05058123 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:58,001] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 2 (__consumer_offsets-0) (reason: Adding new member consumer-3-78aa3221-4245-4ca5-a671-6b4a05058123 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:58,002] INFO [GroupCoordinator 0]: Stabilized group order generation 3 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:26:58,006] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 3 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:27:45,269] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-78aa3221-4245-4ca5-a671-6b4a05058123] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:27:45,269] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 3 (__consumer_offsets-0) (reason: removing member consumer-3-78aa3221-4245-4ca5-a671-6b4a05058123 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:27:45,269] INFO [GroupCoordinator 0]: Group order with generation 4 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:34:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:36:56,152] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-0077e9bb-69f2-47d4-ac49-ef7deeffc6e6] in group product has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:36:56,152] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 5 (__consumer_offsets-15) (reason: removing member consumer-3-0077e9bb-69f2-47d4-ac49-ef7deeffc6e6 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:36:56,152] INFO [GroupCoordinator 0]: Group product with generation 6 is now empty (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:37:07,211] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-7a59356e-2b46-4725-953a-9be38631145a for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:37:07,211] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 4 (__consumer_offsets-0) (reason: Adding new member consumer-3-7a59356e-2b46-4725-953a-9be38631145a with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:37:07,212] INFO [GroupCoordinator 0]: Stabilized group order generation 5 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:37:07,216] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 5 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:38:21,321] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group product in Empty state. Created a new member id consumer-3-e9406098-b30c-40f1-9351-71f04c077776 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:38:21,321] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 6 (__consumer_offsets-15) (reason: Adding new member consumer-3-e9406098-b30c-40f1-9351-71f04c077776 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:38:21,322] INFO [GroupCoordinator 0]: Stabilized group product generation 7 (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:38:21,326] INFO [GroupCoordinator 0]: Assignment received from leader for group product for generation 7 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:44:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:49:29,840] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-7a59356e-2b46-4725-953a-9be38631145a] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:29,840] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 5 (__consumer_offsets-0) (reason: removing member consumer-3-7a59356e-2b46-4725-953a-9be38631145a on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:29,840] INFO [GroupCoordinator 0]: Group order with generation 6 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:42,121] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group order in Empty state. Created a new member id consumer-3-d98113c6-6093-4921-88f1-b4734c8435c7 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:42,122] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 6 (__consumer_offsets-0) (reason: Adding new member consumer-3-d98113c6-6093-4921-88f1-b4734c8435c7 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:42,122] INFO [GroupCoordinator 0]: Stabilized group order generation 7 (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:49:42,125] INFO [GroupCoordinator 0]: Assignment received from leader for group order for generation 7 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:41,742] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-e9406098-b30c-40f1-9351-71f04c077776] in group product has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:41,742] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 7 (__consumer_offsets-15) (reason: removing member consumer-3-e9406098-b30c-40f1-9351-71f04c077776 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:41,742] INFO [GroupCoordinator 0]: Group product with generation 8 is now empty (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:54,214] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group product in Empty state. Created a new member id consumer-3-ccc30d1d-242c-4a00-b709-5940e058b98f for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:54,214] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 8 (__consumer_offsets-15) (reason: Adding new member consumer-3-ccc30d1d-242c-4a00-b709-5940e058b98f with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:54,215] INFO [GroupCoordinator 0]: Stabilized group product generation 9 (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:52:54,219] INFO [GroupCoordinator 0]: Assignment received from leader for group product for generation 9 (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:54:04,743] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2021-09-16 22:57:21,256] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-09-16 22:57:21,260] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2021-09-16 22:57:21,261] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2021-09-16 22:57:21,270] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-ccc30d1d-242c-4a00-b709-5940e058b98f] in group product has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,270] INFO [GroupCoordinator 0]: Preparing to rebalance group product in state PreparingRebalance with old generation 9 (__consumer_offsets-15) (reason: removing member consumer-3-ccc30d1d-242c-4a00-b709-5940e058b98f on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,270] INFO [GroupCoordinator 0]: Group product with generation 10 is now empty (__consumer_offsets-15) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,277] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-54e5eb0c-015e-42fc-beec-c21de5dff7b9] in group delivery has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,277] INFO [GroupCoordinator 0]: Preparing to rebalance group delivery in state PreparingRebalance with old generation 3 (__consumer_offsets-46) (reason: removing member consumer-3-54e5eb0c-015e-42fc-beec-c21de5dff7b9 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,277] INFO [GroupCoordinator 0]: Group delivery with generation 4 is now empty (__consumer_offsets-46) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,281] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-console-consumer-87569-1-82a936b2-53ae-4930-b0e7-a17a27337358] in group console-consumer-87569 has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,281] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-87569 in state PreparingRebalance with old generation 1 (__consumer_offsets-46) (reason: removing member consumer-console-consumer-87569-1-82a936b2-53ae-4930-b0e7-a17a27337358 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,281] INFO [GroupCoordinator 0]: Group console-consumer-87569 with generation 2 is now empty (__consumer_offsets-46) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,295] INFO [GroupCoordinator 0]: Member[group.instance.id None, member.id consumer-3-d98113c6-6093-4921-88f1-b4734c8435c7] in group order has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,295] INFO [GroupCoordinator 0]: Preparing to rebalance group order in state PreparingRebalance with old generation 7 (__consumer_offsets-0) (reason: removing member consumer-3-d98113c6-6093-4921-88f1-b4734c8435c7 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,295] INFO [GroupCoordinator 0]: Group order with generation 8 is now empty (__consumer_offsets-0) (kafka.coordinator.group.GroupCoordinator)
[2021-09-16 22:57:21,578] WARN Session 0x100001825aa0000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2021-09-16 22:57:21,682] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-09-16 22:57:21,682] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2021-09-16 22:57:23,402] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:23,402] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:23,503] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2021-09-16 22:57:25,387] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:25,387] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:27,114] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:27,114] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:28,499] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:28,500] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:30,274] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:30,275] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:31,741] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:31,742] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:32,881] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:32,882] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:34,806] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:34,806] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:36,139] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:36,139] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:37,808] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:37,808] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:39,507] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:39,507] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:41,128] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:41,129] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:42,589] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:42,589] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:43,789] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:43,789] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:45,345] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:45,345] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:46,652] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:46,653] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:47,844] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:47,845] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:49,912] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:49,912] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:51,175] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:51,175] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:53,057] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:53,057] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:54,545] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:54,545] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:56,573] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:56,573] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:58,102] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:58,103] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:59,361] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:57:59,362] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:00,567] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:00,567] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:02,183] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:02,183] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:04,131] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:04,131] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:05,661] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:05,661] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:06,796] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:06,797] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:08,600] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:08,601] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:09,444] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-09-16 22:58:09,444] INFO Terminating process due to signal SIGTERM (org.apache.kafka.common.utils.LoggingSignalHandler)
[2021-09-16 22:58:10,529] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:10,529] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:12,186] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:12,186] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:14,175] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:14,175] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:15,853] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:15,854] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:17,449] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:17,449] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:18,872] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:18,873] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:20,935] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:20,935] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:23,012] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:23,012] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:24,438] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:24,438] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:26,025] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:26,026] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:27,325] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:27,325] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:28,658] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:28,658] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:30,105] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:30,105] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:31,337] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:31,338] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:33,017] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:33,017] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:34,720] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:34,720] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:36,369] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:36,369] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:37,657] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:37,657] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:39,404] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:39,404] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:40,896] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:40,897] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:42,462] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:42,463] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:43,593] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:43,593] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:45,178] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:45,179] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:46,565] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:46,565] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:48,362] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:48,362] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:50,130] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:50,130] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:51,885] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:51,885] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:53,717] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:53,718] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:54,947] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:54,947] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:56,228] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:56,229] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:57,670] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:57,671] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:58,834] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:58,834] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:59,936] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:58:59,936] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:01,937] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:01,937] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:03,646] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:03,646] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:05,473] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:05,473] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:06,705] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:06,705] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:08,533] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:08,533] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:09,747] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:09,748] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:11,292] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:11,292] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:12,867] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:12,867] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:14,153] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:14,154] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:15,318] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:15,319] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:16,781] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:16,781] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:18,134] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:18,135] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:19,611] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:19,612] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:21,099] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:21,099] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:22,771] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:22,771] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:24,255] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:24,255] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:26,310] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:26,310] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:27,618] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:27,618] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:28,930] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:28,930] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:30,280] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:30,280] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:31,580] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:31,581] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:33,553] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:33,554] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:34,965] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:34,965] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:36,631] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:36,631] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:38,192] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2021-09-16 22:59:38,193] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
